### ISSUE TITLE
NV Goggles clear NV effects

### ISSUE THREAD

**Issue by IlyaTheSawmill** [Toma1O6/PUBGMC#1]
Before you use NV Goggles, night vision effects in vanilla can use normally.
after use nv goggles, night vision effects in vanilla will be cleared.

**Comment by Toma1O6** [comment]
The mod is no longer supported.

But the night vision goggles give NV effect which overwrites vanilla effect, so once you stop using it, the effect will be cleared. This is unfortunately expected behaviour
