### ISSUE TITLE
Baubles' GUI blocks Pubgmc's GUI

### ISSUE THREAD

**Issue by Ironnoob73** [Toma1O6/PUBGMC#4]
![image](https://github.com/Toma1O6/PUBGMC/assets/67966070/ba0f9536-5857-4f77-83df-7fb248362f48)
This position is the gui button of baubles, pubgmc's gui button is also in this position, click the baubles button in the lower left corner to open the baubles interface, and the upper right corner to open the pubgmc interface. Can set the button of pubgmc to variable position? Also, can add the inventory slot lock function back?

**Comment by Toma1O6** [comment]
I'll add option to config to change the button's position
